def turn_right():
    turn_left()
    turn_left()
    turn_left()
def Jump():
    turn_left()
    move()
    turn_right()
    move()
    turn_right()
    move()
    turn_left()
def Jump_high():
    turn_left()
    move()
    move()
    move()
    move()
    turn_right()
    move()
    turn_right()
    move()
    move()
    move()
    move()
    turn_left()
def Jump_atlit():
    turn_left()
    move()
    move()
    move()
    turn_right()
    move()
    turn_right()
    move()
    move()
    move()
    turn_left()
def Jump_END():
    turn_left()
    move()
    move()
    turn_right()
    move()
    turn_right()
    move()
    move()
    
move()
Jump_high()
Jump_atlit()
Jump_high()
Jump_high()
move()
move()
move()
Jump_high()
Jump()
Jump()
Jump_END()

################################################################
# WARNING: Do not change this comment.
# Library Code is below.
################################################################